name: release

on:
  push:
    branches:
    - 'release-**'

permissions:
  contents: write # Allow to create a release.

jobs:
  release:
    name: Create draft release
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run:  (echo "RELEASE_TAG=v4.18";echo "RELEASE_GIT_TAG=release-4.18";echo "STAGING_REGISTRY=registry-proxy.engineering.redhat.com"; echo "PROD_REGISTRY=registry-proxy.engineering.redhat.com"; echo "IMAGE_NAME=rh-osbs/openshift-ose-cluster-kube-cluster-api-rhel9-operator") >> $GITHUB_ENV
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --timeout 60m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create draft GH release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            out/operator-components.yaml
            out/package/*
            dist/*.tar.gz
          body: "TODO: Add release notes here."
